import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const src = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8');
const pkg = readFileSync(new URL('../package.json', import.meta.url), 'utf8');
assert.match(src, /<DtecRangeControl display=\{p\.display\} setDisplay=\{p\.setDisplay\}\/><p className="mini">\{p\.rasterStatus\}/, 'dTEC display range lives in Layers immediately after interpolated map opacity');
assert.match(src, /<option value="fixed_0_5">±0\.5 TECU<\/option>/, '±0.5 TECU display range option is available');
assert.match(src, /dtecRangeMode:'fixed_1'/, 'default display range remains fixed ±1.0 TECU');
assert.match(src, /dtecRangeMode==='auto_robust'[\s\S]*Auto robust: ±\{display\.dtecRange\.toFixed\(2\)\} TECU/, 'Auto robust resolved range is displayed');
assert.match(src, /Math\.ceil\(vals\.length\*0\.98\)-1/, 'Auto robust uses the 98th percentile of abs finite dTEC values');
assert.match(src, /Math\.max\(0\.1, Math\.min\(5, raw\)\)/, 'Auto robust clamps to 0.1..5.0 TECU');
assert.match(src, /solarElevationAt\(lon:number, lat:number, solar:any\)[\s\S]*subsolar_latitude[\s\S]*subsolar_longitude/, 'solar elevation is computed from subsolar geometry');
assert.match(src, /viewport\.lon_min-step[\s\S]*viewport\.lon_max\+step/, 'local solar grid covers viewport plus a sampling-cell margin');
assert.match(src, /function marchingSquares[\s\S]*code===5\|\|code===10[\s\S]*center=\(v\[0\]\+v\[1\]\+v\[2\]\+v\[3\]\)\/4/, 'marching-squares cases 5 and 10 use a centre-value asymptotic decider');
assert.match(src, /function stitchSegments[\s\S]*Math\.round\(p\.lon\/tol\)/, 'contour segment endpoints are stitched into continuous polylines with geographic tolerance');
assert.match(src, /normalizeLon\(lon-solar\.subsolar_longitude\)/, 'solar computation handles the antimeridian by normalizing longitude difference');
assert.match(src, /contourPolylines\(solar, threshold, viewport\)\.map\(line=>line\.map/, 'contours are generated and stitched geographically before screen transform');
assert.match(src, /clipPath=\{`url\(#\$\{clipId\}\)`\}/, 'viewport clipping is handled by the shared SVG clipPath');
assert.match(src, /twilightShadingImage\(p\.solarGeometry, p\.layers, v/, 'PNG export uses the current viewport for twilight shading');
assert.match(src, /contourSegments\(p\.solarGeometry,c\.t,x,y,v\)/, 'PNG export uses the same complete contour polylines and current viewport');
assert.match(src, /dtecColor\(pt\.dtec,p\.display\.dtecRange\)/, 'export IPPs use the same resolved dTEC range');
assert.match(src, /dtecColor\(-p\.display\.dtecRange,p\.display\.dtecRange\)/, 'export colorbar uses the same resolved dTEC range');
assert.match(pkg, /dtec-range-and-solar-contours\.test\.mjs/, 'new contour and dTEC range regression tests run under npm test');
console.log('dTEC range and solar contour source checks passed');
