import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Status = { stage: string; current: number; total: number; message: string };
type Manifest = { station_count:number; stations?:string[]; gps_prns:string[]; time_range_hours:{min:number|null;max:number|null}; total_rows_seen:number; valid_rows_after_filters:number; malformed_row_count:number; non_gps_row_count:number; low_elevation_row_count:number; out_of_bounds_row_count:number; applied_filters:Record<string,string|number>; };
type Point = { station:string; time_h:number; prn:string; dtec:number; azimuth:number; elevation:number; ipp_lon:number; ipp_lat:number };
type Arc = { prn:string; arc_index:number; start_time_h:number; end_time_h:number; duration_min:number; row_count:number; station_count:number };
type Series = { station:string; prn:string; points:{time_h:number; dtec:number; elevation:number; ipp_lon:number; ipp_lat:number}[] };
type PanelId = 'summary'|'visibility'|'map'|'timeseries'|'spectral'|'candidates'|'report';
type MapMode = 'epoch'|'satellite'|'window';
const API = 'http://127.0.0.1:8000';
const bounds = { lonMin: -20, lonMax: 50, latMin: 20, latMax: 80 };
const panels:{id:PanelId; n:number; title:string}[] = [
  {id:'summary', n:1, title:'Data import & summary'}, {id:'visibility', n:2, title:'Satellite visibility'}, {id:'map', n:3, title:'Map explorer'}, {id:'timeseries', n:4, title:'Station time series'}, {id:'spectral', n:5, title:'Spectral analysis'}, {id:'candidates', n:6, title:'TID candidates'}, {id:'report', n:7, title:'Event report'},
];

function App() {
  const [folderPath, setFolderPath] = useState('');
  const [status, setStatus] = useState<Status>({ stage: 'idle', current: 0, total: 0, message: 'Idle' });
  const [manifest, setManifest] = useState<Manifest | null>(null);
  const [points, setPoints] = useState<Point[]>([]);
  const [limitReached, setLimitReached] = useState(false);
  const [previewMeta, setPreviewMeta] = useState('');
  const [prn, setPrn] = useState('');
  const [timeH, setTimeH] = useState('0');
  const [startTimeH, setStartTimeH] = useState('');
  const [endTimeH, setEndTimeH] = useState('');
  const [tol, setTol] = useState(15);
  const [maxPoints, setMaxPoints] = useState(5000);
  const [mapMode, setMapMode] = useState<MapMode>('epoch');
  const [arcs, setArcs] = useState<Arc[]>([]);
  const [world, setWorld] = useState<any>(null);
  const [open, setOpen] = useState<Record<PanelId, boolean>>({summary:true, visibility:true, map:true, timeseries:true, spectral:false, candidates:false, report:false});
  const [selected, setSelected] = useState<string[]>([]);
  const [series, setSeries] = useState<Series[]>([]);
  const [selectedLine, setSelectedLine] = useState('');
  const progress = useMemo(() => (status.total > 0 ? Math.round((status.current / status.total) * 100) : 0), [status]);

  useEffect(() => { fetch(`${API}/api/assets/world-borders`).then(r => r.ok ? r.json() : null).then(setWorld).catch(()=>setWorld(null)); }, []);
  useEffect(() => {
    const ws = new WebSocket('ws://127.0.0.1:8000/ws/import-progress');
    ws.onmessage = (event) => { const update = JSON.parse(event.data) as Status; setStatus(update); if (update.stage === 'done') fetch(`${API}/api/manifest`).then((r) => r.json()).then(setManifest); };
    return () => ws.close();
  }, []);

  async function browse() { const r = await fetch(`${API}/api/select-folder`, { method:'POST' }); const j = await r.json(); if (r.ok && j.folder_path) setFolderPath(j.folder_path); else if (!r.ok) setStatus({stage:'error', current:0, total:0, message:j.detail || 'Folder dialog failed'}); }
  async function startImport() { setManifest(null); setPoints([]); setArcs([]); const response = await fetch(`${API}/api/import`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ folder_path: folderPath }) }); if (!response.ok) setStatus({ stage:'error', current:0, total:0, message:await response.text() }); }
  async function loadVisibility() { const j = await fetch(`${API}/api/satellites/visibility`).then(r=>r.json()); setArcs(j.arcs || []); }
  async function loadPreview() { const q = new URLSearchParams({ tolerance_seconds:String(tol), max_points:String(maxPoints) }); if (prn) q.set('prn', prn); if (mapMode === 'epoch' && timeH !== '') q.set('time_h', timeH); if (mapMode === 'window') { if (startTimeH !== '') q.set('start_time_h', startTimeH); if (endTimeH !== '') q.set('end_time_h', endTimeH); } const j = await fetch(`${API}/api/preview/points?${q}`).then(r=>r.json()); setPoints(j.points || []); setLimitReached(Boolean(j.limit_reached)); setPreviewMeta(`${j.mode_used}; ${j.count_returned}/${j.total_matching_before_limit} points`); }
  function chooseArc(a:Arc) { setPrn(a.prn); setTimeH(String(((a.start_time_h + a.end_time_h) / 2).toFixed(4))); setStartTimeH(String(a.start_time_h)); setEndTimeH(String(a.end_time_h)); setMapMode('epoch'); setOpen(o=>({...o,map:true})); }
  function step(minutes:number) { setTimeH(v => String(Math.max(0, (Number(v || 0) + minutes / 60)).toFixed(4))); }
  function toggleStation(p:Point) { const id = `${p.station}|${p.prn}`; setSelected(s => s.includes(id) ? s.filter(x=>x!==id) : [...s, id]); }
  async function loadSeries() { const stations = selected.map(s=>s.split('|')[0]); const usePrn = prn || selected[0]?.split('|')[1]; if (!usePrn || !stations.length) return; const q = new URLSearchParams({ prn: usePrn }); stations.forEach(s=>q.append('station', s)); if (startTimeH) q.set('start_time_h', startTimeH); if (endTimeH) q.set('end_time_h', endTimeH); const j = await fetch(`${API}/api/stations/timeseries?${q}`).then(r=>r.json()); setSeries(j.series || []); }

  return <div className="app">
    <header className="topbar"><span className="brand">TID Analyzer</span><input value={folderPath} onChange={e=>setFolderPath(e.target.value)} placeholder="Local daily folder path" /><button onClick={browse}>Browse…</button><button onClick={startImport}>Import</button><progress value={progress} max="100" /><span>{status.message}</span>{manifest && <span className="mini">Stations {manifest.station_count} · PRNs {manifest.gps_prns.length} · Valid {manifest.valid_rows_after_filters}</span>}</header>
    <main className="workspace"><section className="canvas"><div className="canvasHead"><h1>Map Explorer</h1><span>{previewMeta}{limitReached ? ' · sampled limit reached' : ''}</span></div><PreviewPlot points={points} world={world} selected={selected} onPointClick={toggleStation}/></section><aside className="side">{panels.map(p=><WorkflowPanel key={p.id} panel={p} open={open[p.id]} toggle={()=>setOpen(o=>({...o,[p.id]:!o[p.id]}))}>{p.id==='summary' && <Summary manifest={manifest}/>} {p.id==='visibility' && <Visibility arcs={arcs} load={loadVisibility} choose={chooseArc}/>} {p.id==='map' && <Explorer manifest={manifest} prn={prn} setPrn={setPrn} timeH={timeH} setTimeH={setTimeH} startTimeH={startTimeH} setStartTimeH={setStartTimeH} endTimeH={endTimeH} setEndTimeH={setEndTimeH} tol={tol} setTol={setTol} maxPoints={maxPoints} setMaxPoints={setMaxPoints} loadPreview={loadPreview} count={points.length} limitReached={limitReached} mapMode={mapMode} setMapMode={setMapMode} step={step}/>} {p.id==='timeseries' && <TimeSeries selected={selected} setSelected={setSelected} load={loadSeries} series={series} selectedLine={selectedLine} setSelectedLine={setSelectedLine}/>} {p.id==='spectral' && <Placeholder text={selectedLine ? `Selected ${selectedLine}. FFT and Morlet endpoints are TODO.` : 'Select a time-series line to enable FFT and Morlet placeholders.'}/>} {p.id==='candidates' && <Placeholder text="TID candidate detection placeholder."/>} {p.id==='report' && <Placeholder text="Event report and export placeholder."/>}</WorkflowPanel>)}</aside></main>
    <footer>References · dTEC is vertical dTEC · IPP height 450 km · GPS PRN prefix G · min elevation 50°</footer>
  </div>;
}
function WorkflowPanel({panel,open,toggle,children}:any) { return <section className="workflow"><div className="workflowTitle"><button onClick={toggle}>{open?'▾':'▸'} {panel.n}. {panel.title}</button><button disabled>Enlarge</button></div>{open && <div className="workflowBody">{children}</div>}</section>; }
function Summary({manifest}:{manifest:Manifest|null}) { if(!manifest) return <p className="placeholder">Import a folder to view metadata.</p>; return <div className="summary"><p><b>Stations:</b> {manifest.station_count}</p><p><b>GPS PRNs:</b> {manifest.gps_prns.join(', ') || 'None'}</p><p><b>Time range:</b> {manifest.time_range_hours.min}–{manifest.time_range_hours.max} h</p><p><b>Rows:</b> {manifest.valid_rows_after_filters} valid / {manifest.total_rows_seen} seen</p><p className="mini">Filters: GPS, elevation ≥50°, lon -20..50, lat 20..80.</p></div>; }
function Visibility({arcs,load,choose}:any) { return <div><button onClick={load}>Load visibility</button><table><thead><tr><th>PRN</th><th>arc</th><th>start</th><th>end</th><th>min</th><th>rows</th><th>sta</th></tr></thead><tbody>{arcs.map((a:Arc)=><tr key={`${a.prn}-${a.arc_index}`} onClick={()=>choose(a)}><td>{a.prn}</td><td>{a.arc_index}</td><td>{a.start_time_h.toFixed(2)}</td><td>{a.end_time_h.toFixed(2)}</td><td>{a.duration_min.toFixed(1)}</td><td>{a.row_count}</td><td>{a.station_count}</td></tr>)}</tbody></table></div>; }
function Explorer(p:any) { return <div className="summary"><label>Mode <select value={p.mapMode} onChange={(e:any)=>p.setMapMode(e.target.value)}><option value="epoch">Current epoch</option><option value="satellite">Whole selected satellite</option><option value="window">Selected time window</option></select></label><label>PRN <select value={p.prn} onChange={(e:any)=>p.setPrn(e.target.value)}><option value="">All</option>{p.manifest?.gps_prns.map((x:string)=><option key={x}>{x}</option>)}</select></label>{p.mapMode==='epoch' && <><label>Time (h) <input value={p.timeH} onChange={(e:any)=>p.setTimeH(e.target.value)}/></label><div className="buttonRow">{[-15,-5,-0.5,0.5,5,15].map(m=><button key={m} onClick={()=>p.step(m)}>{m>0?'+':''}{m===-0.5?'- prev epoch':m===0.5?'next epoch':`${m} min`}</button>)}</div><label>Tolerance seconds <input type="number" value={p.tol} onChange={(e:any)=>p.setTol(Number(e.target.value))}/></label></>}{p.mapMode==='window' && <><label>Start h <input value={p.startTimeH} onChange={(e:any)=>p.setStartTimeH(e.target.value)}/></label><label>End h <input value={p.endTimeH} onChange={(e:any)=>p.setEndTimeH(e.target.value)}/></label></>}<label>Max points <input type="number" value={p.maxPoints} onChange={(e:any)=>p.setMaxPoints(Number(e.target.value))}/></label><button onClick={p.loadPreview}>Load preview points</button><div className="buttonRow"><button disabled>Export PNG</button><button disabled>Export GIF</button></div><p>Returned points: {p.count} {p.limitReached ? '(deterministic sample)' : ''}</p></div>; }
function TimeSeries({selected,setSelected,load,series,selectedLine,setSelectedLine}:any) { return <div><p>{selected.length ? selected.map((s:string)=><button key={s} onClick={()=>setSelected((x:string[])=>x.filter(y=>y!==s))}>{s} ×</button>) : <span className="placeholder">Click map points to select station/PRN.</span>}</p><button onClick={load} disabled={!selected.length}>Load time series</button><button onClick={()=>setSelected([])}>Clear</button><SeriesPlot series={series} selectedLine={selectedLine} setSelectedLine={setSelectedLine}/></div>; }
function Placeholder({text}:{text:string}) { return <p className="placeholder">{text}<br/><button disabled>Compute FFT</button> <button disabled>Compute Morlet</button></p>; }
function PreviewPlot({points,world,selected,onPointClick}:any) { const [tip,setTip]=useState(''); const w=820,h=560,pad=55; const x=(lon:number)=>pad+(lon-bounds.lonMin)/(bounds.lonMax-bounds.lonMin)*(w-2*pad); const y=(lat:number)=>h-pad-(lat-bounds.latMin)/(bounds.latMax-bounds.latMin)*(h-2*pad); const max=Math.max(1,...points.map((p:Point)=>Math.abs(p.dtec))); const color=(v:number)=>v<0?`rgb(${255+v/max*155},${255+v/max*155},255)`: `rgb(255,${255-v/max*155},${255-v/max*155})`; return <><svg viewBox={`0 0 ${w} ${h}`} className="plot">{[-20,0,20,40,50].map(l=><g key={'x'+l}><line x1={x(l)} x2={x(l)} y1={pad} y2={h-pad}/><text x={x(l)} y={h-18}>{l}°</text></g>)}{[20,40,60,80].map(l=><g key={'y'+l}><line x1={pad} x2={w-pad} y1={y(l)} y2={y(l)}/><text x={12} y={y(l)}>{l}°</text></g>)}<Borders world={world} x={x} y={y}/>{points.map((p:Point,i:number)=>{const id=`${p.station}|${p.prn}`; const sel=selected.includes(id); return <circle key={i} cx={x(p.ipp_lon)} cy={y(p.ipp_lat)} r={sel?7:4} fill={color(p.dtec)} stroke={sel?'#ffe66d':'#06101d'} onClick={()=>onPointClick(p)} onMouseEnter={()=>setTip(`${p.station} ${p.prn} dTEC=${p.dtec} time=${p.time_h}h elev=${p.elevation} lon=${p.ipp_lon} lat=${p.ipp_lat}`)} />})}</svg><p className="tooltip">{tip || 'Click IPP points to toggle station selection.'}</p></>; }
function Borders({world,x,y}:any){ if(!world?.features) return null; const paths:string[]=[]; const add=(coords:any[])=>{let d=''; coords.forEach((c:any,i:number)=>{ if(c[0]<bounds.lonMin||c[0]>bounds.lonMax||c[1]<bounds.latMin||c[1]>bounds.latMax) return; d += `${d?'L':'M'}${x(c[0])},${y(c[1])}`; }); if(d) paths.push(d); }; world.features.forEach((f:any)=>{const g=f.geometry; if(!g) return; if(g.type==='LineString') add(g.coordinates); if(g.type==='Polygon') g.coordinates.forEach(add); if(g.type==='MultiPolygon') g.coordinates.flat().forEach(add);}); return <g className="borders">{paths.map((d,i)=><path key={i} d={d}/>)}</g>; }
function SeriesPlot({series,selectedLine,setSelectedLine}:any){ if(!series?.length) return null; const pts=series.flatMap((s:Series)=>s.points); if(!pts.length) return <p className="placeholder">No time-series points.</p>; const w=330,h=190,pad=28; const minT=Math.min(...pts.map((p:any)=>p.time_h)), maxT=Math.max(...pts.map((p:any)=>p.time_h)); const minD=Math.min(...pts.map((p:any)=>p.dtec)), maxD=Math.max(...pts.map((p:any)=>p.dtec)); const x=(t:number)=>pad+(t-minT)/Math.max(1e-9,maxT-minT)*(w-2*pad); const y=(d:number)=>h-pad-(d-minD)/Math.max(1e-9,maxD-minD)*(h-2*pad); return <svg viewBox={`0 0 ${w} ${h}`} className="series">{series.map((s:Series,i:number)=>{const key=`${s.station}|${s.prn}`; const d=s.points.map((p,j)=>`${j?'L':'M'}${x(p.time_h)},${y(p.dtec)}`).join(''); return <path key={key} d={d} className={selectedLine===key?'line selectedLine':'line'} style={{stroke:['#66d9ff','#ffc857','#7ee081','#ff6b9a'][i%4]}} onClick={()=>setSelectedLine(key)}/>})}</svg>; }
createRoot(document.getElementById('root')!).render(<App />);
